task:
  name: stable x86_64-unknown-freebsd-12
  freebsd_instance:
    image: freebsd-14-0-snap
  sysinfo_script:
    - id
    - uname -a
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo clippy --verbose
    - cargo test --verbose

task:
  name: stable x86_64-unknown-freebsd-13
  freebsd_instance:
    image: freebsd-13-2
  sysinfo_script:
    - id
    - uname -a
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo clippy --verbose
    - cargo test --verbose

task:
  name: stable aarch64-apple-darwin
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  sysinfo_script:
    - id
    - uname -a
  setup_script:
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    - . $HOME/.cargo/env
  test_script:
    - . $HOME/.cargo/env
    - cargo clippy --verbose
    - cargo test --verbose
